production:
  # KEYS
  STRIPE_PUBLISHABLE_KEY: "pk_test_xrqiMRPnwPPz8cDPsiEKtgAa"
  STRIPE_SECRET_KEY: "sk_test_35msZ8Pbnqvyih0Nfe90l9Fq"
  CLOUDINARY_URL: "cloudinary://139741217945453:8Ks0bUkJsQ8LAiF0UPDo7MN4B78@dbhsa0hgf"
  CLOUDINARY_NAME: "dbhsa0hgf"
  GOOGLE_API_BROWSER_KEY: "AIzaSyDQ-CtTAfoyjiLEkFdwB5nZejFmBfIY4Eo"
  GOOGLE_API_SERVER_KEY: "AIzaSyDQ-CtTAfoyjiLEkFdwB5nZejFmBfIY4Eo"
  FB_ID: "937179443099115"
  FB_SECRET: "75720dfc0997286a7a5186bf42428877"
  ALGOLIA_API_KEY: "2108c06a7c74c7d4c64b52e63cc2a8ef"
  ALGOLIAPPID: "SBTERHV352"
  ALGOLISEARCHKEY: "959036b3f757a9f94938c6d46a03c2d5"
  LAPOSTE_API_KEY: "lbcSgDW3tBaixIKP/XH0bsMYiKEhPaS6E/gUw+RJmkigGw4+qUNl5uy8/Ilx4eWh"
  # FIGURE PARAMETERS
  LESSONDEPOSITRATIO: "0.5"
  CAPACITY: "6"
  MINBOOKING: "2"
  MINDURATION:  "2"
  MAXDURATION: "5"
  TWODAYSLESSONPRICE: "150.0"
  FIVEDAYSLESSONPRICE: "380.0"
  PERIODTOLOOKFORLESSON: "14"
  BASKETDURATION: "0.5"
  TVA: "0.2"
  # APP & OWNER
  APPNAME: "ecommercebase"
  LASTNAME: "Kaltenbacher"
  FIRSTNAME: "Carole"
  TELEPHONE: "+33000000000"
  ADDRESS: "6+rue+des+verdiers+NIEDERHAUSBERGEN" # --> ADDRESS: "12+Rue+du+Bignon+44260+Savenay" OK
  LAT: "48.6229537"
  LNG: "7.705769"
  MODEL: "produits"
  EMAIL: "gcrouillere@hotmail.fr"
  # IMAGES
  HOMEPIC: "home-base.jpg"
  HOMEPICMOBILE: "home-base-mobile.jpg"
  STAGEPIC: "stage.jpg"
  SHIPPIC: "ship.svg"
  AVATAR: "avatar.jpg"
  CITY: "city.jpg"
  LOGOSITE: "logo.png"
  HOMERIGHTPHOTO: "avatar.jpg"
  DARKTHEMEPHOTO: "darkthemehome1.jpg"

development:
  # KEYS
  STRIPE_PUBLISHABLE_KEY: "pk_test_xrqiMRPnwPPz8cDPsiEKtgAa"
  STRIPE_SECRET_KEY: "sk_test_35msZ8Pbnqvyih0Nfe90l9Fq"
  CLOUDINARY_URL: "cloudinary://139741217945453:8Ks0bUkJsQ8LAiF0UPDo7MN4B78@dbhsa0hgf"
  CLOUDINARY_NAME: "dbhsa0hgf"
  GOOGLE_API_BROWSER_KEY: "AIzaSyDQ-CtTAfoyjiLEkFdwB5nZejFmBfIY4Eo"
  GOOGLE_API_SERVER_KEY: "AIzaSyDQ-CtTAfoyjiLEkFdwB5nZejFmBfIY4Eo"
  FB_ID: "2001916366750860"
  FB_SECRET: "0828c4eaccd049002148c19507325dc6"
  ALGOLIA_API_KEY: "2108c06a7c74c7d4c64b52e63cc2a8ef"
  ALGOLIAPPID: "SBTERHV352"
  ALGOLISEARCHKEY: "959036b3f757a9f94938c6d46a03c2d5"
  LAPOSTE_API_KEY: "lbcSgDW3tBaixIKP/XH0bsMYiKEhPaS6E/gUw+RJmkigGw4+qUNl5uy8/Ilx4eWh"
  # FIGURE PARAMETERS
  LESSONDEPOSITRATIO: "0.5"
  CAPACITY: "6"
  MINBOOKING: "2"
  MINDURATION:  "2"
  MAXDURATION: "5"
  TWODAYSLESSONPRICE: "150.0"
  FIVEDAYSLESSONPRICE: "380.0"
  PERIODTOLOOKFORLESSON: "14"
  BASKETDURATION: "0.016"
  TVA: "0.2"
  # APP & OWNER
  APPNAME: "ecommercebase"
  LASTNAME: "Toutlemonde"
  FIRSTNAME: "Mme"
  TELEPHONE: "+33000000000"
  ADDRESS: "12+Rue+du+Bignon+44260+Savenay" # --> ADDRESS: "12+Rue+du+Bignon+44260+Savenay" OK
  LAT: "44.031792"
  LNG: "1.94926"
  MODEL: "produits"
  EMAIL: "gcrouillere@hotmail.fr"
  # IMAGES
  HOMEPIC: "home-base.jpg"
  HOMEPICMOBILE: "home-base-mobile.jpg"
  STAGEPIC: "stage.jpg"
  SHIPPIC: "ship.svg"
  AVATAR: "avatar.jpg"
  CITY: "city.jpg"
  LOGOSITE: "logo.png"
  HOMERIGHTPHOTO: "avatar.jpg"
  DARKTHEMEPHOTO: "darkthemehome1.jpg"
